### ISSUE TITLE
Not receiving message from client to client

### ISSUE THREAD

**Issue by Ben-Ortiz** [henrychu04/CS419-Computer-Security-Project#1]
When i start server and open 2 client terminals, the messages are sent to the server terminal, but it can't be seen in the client terminals unless history is checked between the 2 clients

**Comment by henrychu04** [comment]
This is exactly how it's supposed to work

**Comment by Ben-Ortiz** [comment]
ahh ok

**Comment by Ben-Ortiz** [comment]
so you can't communicate between client to client just client to server?

**Comment by henrychu04** [comment]
The server stores all the encrypted messages, and depending on the client's username, the client is able to access and decrypt the messages stored on the server

**Comment by Ben-Ortiz** [comment]
ok i see

**Comment by symxmyz233** [comment]
**It is not a bug**
